Fix for Invalid Blocked Path
This is to fix the following problem when accessFileSysViaSudo=true:
ERROR>sudo: unknown user: null
java.lang.RuntimeException: No such path: [/]. Invalid blocked local path input.

I have added a failback if uid is null to use the File.exists() using the current user and to print a warning in this case.  I have tested this issue and Junmin has approved.



git-svn-id: https://codeforge.lbl.gov/anonscm/bestman@69 f407c832-ab63-4b9d-b5b1-2a9f91e557d8